In [30]:
from sympy import *
import numpy as np
import math

## diff((math.sin(x^2)*x),x)
from sympy import *

diff((math.sin(x)),x)

2*x**2*cos(x**2) + sin(x**2)

In [6]:
def deriv(f):
    dx=0.00000001
    return lambda x: (f(x+dx)-f(x))/dx

print(deriv(lambda x:x**3))

<function deriv.<locals>.<lambda> at 0x107e3e730>


In [9]:
data = np.array(range(5), dtype = int)
data
# array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [10]:
data2 = np.asarray(data)
data2 is data
# True

True

In [11]:
np.arange(1, 16, 2)
# array([ 1,  3,  5,  7,  9, 11, 13, 15])

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [14]:
ndarry = np.random.randn(100)
ndarry

array([ 0.46203936,  0.57887028, -0.48350971, -0.17259144,  0.29522084,
       -0.17623504, -1.36532517, -0.64192032,  0.25113715, -3.05718421,
       -1.52745125,  1.36497862,  0.50262308, -1.30090939, -2.12065487,
        0.13114586,  1.73296558,  0.31752394,  0.50502705,  0.83079067,
       -0.73750229,  0.30729387, -1.37924159,  1.65830623, -1.66325065,
        2.80588447,  1.16671363,  0.58499255, -0.90488892,  0.15613594,
        1.68066984,  0.93728315, -0.48760476, -1.24855738, -1.78952993,
        0.81968322, -0.54783846, -0.3298728 ,  0.17173561, -0.68799777,
       -0.28825041,  1.59110807, -1.42061554,  0.38245814, -0.79072257,
       -0.54189597,  0.33772388,  0.21447541, -0.40996156, -0.2613834 ,
       -1.08494475, -1.13936924,  0.85323616, -0.84757064,  0.30262732,
       -0.96961367, -0.91307307, -0.88504549, -0.90401163,  0.17641013,
        0.34576371, -1.22216959,  1.50756347,  1.98750191, -0.45706163,
       -0.58342207, -0.60424691,  1.7362609 ,  0.24633229, -1.05

In [15]:
ndarry[ndarry < 0] = 0
ndarry

array([ 0.46203936,  0.57887028,  0.        ,  0.        ,  0.29522084,
        0.        ,  0.        ,  0.        ,  0.25113715,  0.        ,
        0.        ,  1.36497862,  0.50262308,  0.        ,  0.        ,
        0.13114586,  1.73296558,  0.31752394,  0.50502705,  0.83079067,
        0.        ,  0.30729387,  0.        ,  1.65830623,  0.        ,
        2.80588447,  1.16671363,  0.58499255,  0.        ,  0.15613594,
        1.68066984,  0.93728315,  0.        ,  0.        ,  0.        ,
        0.81968322,  0.        ,  0.        ,  0.17173561,  0.        ,
        0.        ,  1.59110807,  0.        ,  0.38245814,  0.        ,
        0.        ,  0.33772388,  0.21447541,  0.        ,  0.        ,
        0.        ,  0.        ,  0.85323616,  0.        ,  0.30262732,
        0.        ,  0.        ,  0.        ,  0.        ,  0.17641013,
        0.34576371,  0.        ,  1.50756347,  1.98750191,  0.        ,
        0.        ,  0.        ,  1.7362609 ,  0.24633229,  0.  